package opencode

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/danielsampar12/odin/internal/config"
	ollamaplugin "github.com/danielsampar12/odin/internal/plugins/ollama"
)

const ManagedMarker = "Generated by Odin v2"

var ErrUnmanagedGeneratedConfig = errors.New("existing OpenCode config is not Odin-managed")

type ProjectScaffold struct {
	ProjectDir          string
	ConfigPath          string
	RuntimeProvider     string
	RuntimeBaseURL      string
	OpenAICompatibleURL string
	Model               string
	Companion           string
}

type WriteResult struct {
	Path        string
	Written     bool
	Updated     bool
	OdinManaged bool
}

func ResolveProjectScaffold(cwd string) (ProjectScaffold, error) {
	globalConfigPath := config.GlobalConfigPath()
	projectConfigPath := config.ProjectConfigPath(cwd)

	runtimeProvider := "ollama"
	if value, err := config.ReadGlobalRuntimeProvider(globalConfigPath); err == nil && value != "" {
		runtimeProvider = value
	}
	if value, err := config.ReadProjectRuntimeProvider(projectConfigPath); err == nil && value != "" {
		runtimeProvider = value
	}

	modelName := "qwen2.5-coder:7b"
	if value, err := config.ReadGlobalModelDefault(globalConfigPath); err == nil && value != "" {
		modelName = value
	}
	if value, err := config.ReadProjectModelDefault(projectConfigPath); err == nil && value != "" {
		modelName = value
	}

	companion := "baldur"
	if value, err := config.ReadGlobalCompanionDefault(globalConfigPath); err == nil && value != "" {
		companion = value
	}
	if value, err := config.ReadProjectCompanionDefault(projectConfigPath); err == nil && value != "" {
		companion = value
	}

	baseURL := config.ResolveGlobalRuntimeBaseURL(globalConfigPath, ollamaplugin.DefaultBaseURL)

	return ProjectScaffold{
		ProjectDir:          cwd,
		ConfigPath:          config.ProjectGeneratedOpenCodeConfigPath(cwd),
		RuntimeProvider:     runtimeProvider,
		RuntimeBaseURL:      baseURL,
		OpenAICompatibleURL: ensureV1Endpoint(baseURL),
		Model:               modelName,
		Companion:           companion,
	}, nil
}

func (s ProjectScaffold) Supported() bool {
	return strings.EqualFold(s.RuntimeProvider, "ollama")
}

func (s ProjectScaffold) ProviderModel() string {
	return "ollama/" + s.Model
}

func (s ProjectScaffold) RenderJSONC() (string, error) {
	payload := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"provider": map[string]any{
			"ollama": map[string]any{
				"npm":  "@ai-sdk/openai-compatible",
				"name": "Ollama (local)",
				"options": map[string]any{
					"baseURL": s.OpenAICompatibleURL,
				},
				"models": map[string]any{
					s.Model: map[string]any{
						"name": s.Model,
					},
				},
			},
		},
		"model":        s.ProviderModel(),
		"instructions": []string{"../rules.md"},
	}

	body, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return "", err
	}

	return fmt.Sprintf(`// %s.
// Project-local OpenCode config scaffold for Odin.
// Safe to regenerate with "odin opencode generate".
// Selected companion: %s
// Uses OPENCODE_CONFIG=%s when launching OpenCode.
%s
`, ManagedMarker, s.Companion, filepath.ToSlash(filepath.Join(".odin", "generated", "opencode.jsonc")), string(body)), nil
}

func WriteGeneratedConfig(cwd string, force bool) (WriteResult, error) {
	scaffold, err := ResolveProjectScaffold(cwd)
	if err != nil {
		return WriteResult{}, err
	}

	if !scaffold.Supported() {
		return WriteResult{}, fmt.Errorf("unsupported runtime provider %q; OpenCode generation currently supports Ollama only", scaffold.RuntimeProvider)
	}

	content, err := scaffold.RenderJSONC()
	if err != nil {
		return WriteResult{}, err
	}

	if err := os.MkdirAll(config.ProjectGeneratedDir(cwd), 0o755); err != nil {
		return WriteResult{}, err
	}

	result := WriteResult{Path: scaffold.ConfigPath}
	existing, err := os.ReadFile(scaffold.ConfigPath)
	if err == nil {
		result.OdinManaged = strings.Contains(string(existing), ManagedMarker)
		if !force && !result.OdinManaged {
			return result, ErrUnmanagedGeneratedConfig
		}
		result.Updated = true
		if string(existing) == content {
			return result, nil
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return result, err
	}

	if err := os.WriteFile(scaffold.ConfigPath, []byte(content), 0o644); err != nil {
		return result, err
	}

	result.Written = true
	return result, nil
}

func LaunchCommand() string {
	return "OPENCODE_CONFIG=.odin/generated/opencode.jsonc opencode ."
}

func ensureV1Endpoint(baseURL string) string {
	trimmed := strings.TrimRight(baseURL, "/")
	if strings.HasSuffix(trimmed, "/v1") {
		return trimmed
	}
	return trimmed + "/v1"
}
